name: Deploy website on push to cPanel
on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    steps:
      - name: Upload to cPanel 📂
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
